---

- name: install nginx
  apt:
    name: nginx
    state: present

- name: upload nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - reload-nginx

- name: upload firewall rules for nginx
  template:
    src: firewall.sh
    dest: /etc/firewall/nginx.sh
    mode: 0750
  notify:
    - restart-firewall

- name: upload nginx's after ssl renew script
  template:
    src: after-ssl-renew.sh
    dest: /etc/ssl/letsencrypt/after-renew.d
    mode: 0750

- name: create systemd override file
  template:
    src: override.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf
